[package]
name = "part3"
version = "0.1.0"
authors = ["ukasha <ukasha909@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
